### PR TITLE
2nCSWz0q-Feature-Landing-page

### PR DESCRIPTION
**Pull request by ihonore**

### CODE REVIEW

**Review by CYIMANA-Faisal — COMMENTED** [review]
Have the landing page responsive and also lint your code before you push them. try to use naming conventions that are meaningful. the screen size to be fitting for the landing transparent image and whole page.

**Comment by ihonore** [comment]
Fixed the responsiveness and naming conventions

**Comment by CYIMANA-Faisal** [comment]
@ihonore  Can you name the title of this PR using the Andela's naming conventions

**Comment by CYIMANA-Faisal** [comment]
Let me know if you have the PR template file in your GitHub repo

**Pull request closed without merging**
